CREATE TABLE IF NOT EXISTS ulda_record (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  sign BYTEA NOT NULL,
  data BYTEA NOT NULL,
  create_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  update_time TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
