CREATE TABLE IF NOT EXISTS ulda_records (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  sign BYTEA NOT NULL,
  data BYTEA NOT NULL,
  create_time TIMESTAMPTZ NOT NULL,
  update_time TIMESTAMPTZ NOT NULL
);
